javax:
  sql:
    DataSource:
      customerDataSource:
        dataSourceClassName: org.postgresql.ds.PGSimpleDataSource
        dataSource:
          url: jdbc:postgresql://fanny.db.elephantsql.com:5432/apmygctp
          user: apmygctp
          password: cIOFosqRjrP03S3_7DDKIz10vJHH-Ojg