javax:
  sql:
    DataSource:
      customerDataSource:
        dataSourceClassName: org.postgresql.ds.PGSimpleDataSource
        dataSource:
          url: jdbc:postgresql://localhost:5432/proyectogrupal
          user: postgres
          password: "p4ch1tR3x"